// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proxy/mieru/config.proto

package mieru

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account 是 mieru 的用户凭据。mieru 用 username+password 派生 AEAD key
// (SHA256/PBKDF2/timeSalt),多用户时服务端用 nonce 末 4 字节的 userTag 快速定位用户后试解。
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// 传输层:目前仅 "tcp"(UDP underlay 为后续阶段)。
	Transport     string `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

var File_proxy_mieru_config_proto protoreflect.FileDescriptor

const file_proxy_mieru_config_proto_rawDesc = "" +
	"\n" +
	"\x18proxy/mieru/config.proto\x12\x10xray.proxy.mieru\x1a\x1acommon/protocol/user.proto\"A\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"^\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransportBR\n" +
	"\x14com.xray.proxy.mieruP\x01Z%github.com/xtls/xray-core/proxy/mieru\xaa\x02\x10Xray.Proxy.Mierub\x06proto3"

var (
	file_proxy_mieru_config_proto_rawDescOnce sync.Once
	file_proxy_mieru_config_proto_rawDescData []byte
)

func file_proxy_mieru_config_proto_rawDescGZIP() []byte {
	file_proxy_mieru_config_proto_rawDescOnce.Do(func() {
		file_proxy_mieru_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)))
	})
	return file_proxy_mieru_config_proto_rawDescData
}

var file_proxy_mieru_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_mieru_config_proto_goTypes = []any{
	(*Account)(nil),       // 0: xray.proxy.mieru.Account
	(*ServerConfig)(nil),  // 1: xray.proxy.mieru.ServerConfig
	(*protocol.User)(nil), // 2: xray.common.protocol.User
}
var file_proxy_mieru_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.mieru.ServerConfig.users:type_name -> xray.common.protocol.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_mieru_config_proto_init() }
func file_proxy_mieru_config_proto_init() {
	if File_proxy_mieru_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mieru_config_proto_goTypes,
		DependencyIndexes: file_proxy_mieru_config_proto_depIdxs,
		MessageInfos:      file_proxy_mieru_config_proto_msgTypes,
	}.Build()
	File_proxy_mieru_config_proto = out.File
	file_proxy_mieru_config_proto_goTypes = nil
	file_proxy_mieru_config_proto_depIdxs = nil
}
