server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {domain};

    ssl_certificate /usr/local/nginx/cert/{cert_name}.pem;
    ssl_certificate_key /usr/local/nginx/cert/{cert_name}.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root {static_root_path};
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
